name: health
description: Wrapper for the iOS HealthKit and Android GoogleFit services.
version: 4.5.0
homepage: https://github.com/cph-cachet/flutter-plugins/tree/master/packages/health

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^9.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: cachet.plugins.health
        pluginClass: HealthPlugin
      ios:
        pluginClass: HealthPlugin
